const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

async function generateResumePdf({
  resumeData,
  photoUrl,
  userName,
  outputPath,
}) {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filepath = outputPath + '.pdf';

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  const {
    fullName,
    qualifications,
    experience,
    personalInfo,
  } = resumeData || {};

  const displayName = fullName || userName || '';

  doc.fontSize(24).font('Helvetica-Bold').text(displayName || 'Resume', { align: 'left' });
  doc.moveDown(0.2);
  doc.fontSize(9).font('Helvetica').fillColor('gray').text('Generated by InternArea Premium Resume', { align: 'left' });
  doc.moveDown(0.5);

  if (photoUrl) {
    try {
      const response = await fetch(photoUrl);
      if (response.ok) {
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        doc.rect(430, 50, 92, 92).fill('#f3f4f6');
        doc.image(buffer, 430, 50, { width: 92, height: 92 });
      }
    } catch (e) {
      // If photo fetch fails, skip the photo — don't block PDF generation.
    }
  }

  // Personal Information
  doc.moveDown();
  doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Personal Information', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('black');
  const kv = [
    ['Email', personalInfo?.email],
    ['Phone', personalInfo?.phone],
    ['Location', personalInfo?.location],
    ['LinkedIn', personalInfo?.linkedin],
    ['Website', personalInfo?.website],
  ];
  for (const [k, v] of kv) {
    if (v !== undefined && v !== null && v !== '') {
      doc.text(`${k}: ${v}`);
    }
  }

  // Qualifications
  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Qualifications', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('black');
  writeTextBlock(doc, qualifications, false);

  // Experience
  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Experience', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica').fillColor('black');
  writeTextBlock(doc, experience, true);

  doc.moveDown(1);
  doc.fontSize(8).font('Helvetica').fillColor('gray').text('This document was generated after successful payment verification.', { align: 'center' });

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return filepath;
}

function writeTextBlock(doc, block, allowBullets) {
  if (!block) {
    doc.fillColor('gray').text('Not provided.', { align: 'left' });
    return;
  }

  if (typeof block === 'string') {
    if (allowBullets) {
      const lines = block.split('\n').filter((l) => l.trim() !== '');
      lines.forEach((line) => doc.list([line], { bulletIndent: 30, textIndent: 10 }));
    } else {
      doc.text(block);
    }
    return;
  }

  if (Array.isArray(block) && block.length > 0) {
    if (allowBullets) {
      doc.list(block.map((x) => String(x)), { bulletIndent: 30, textIndent: 10 });
    } else {
      block.forEach((x) => doc.text(String(x)));
    }
    return;
  }

  doc.text(typeof block === 'object' ? JSON.stringify(block, null, 2) : String(block));
}

module.exports = {
  generateResumePdf,
};
